# Generated by Django 6.0 on 2025-12-25 21:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0002_alter_organization_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="User-friendly name for this AWS account (e.g., 'Production', 'Staging')", max_length=255)),
                ('aws_account_id', models.CharField(blank=True, help_text='The 12-digit AWS account ID (populated after verification)', max_length=12)),
                ('external_id', models.UUIDField(default=uuid.uuid4, help_text='External ID for secure cross-account AssumeRole')),
                ('role_arn', models.CharField(blank=True, help_text='IAM role ARN that DevOpsHero assumes for deployments', max_length=2048)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('error', 'Error')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='Additional status information or error details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_aws_accounts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aws_accounts', to='devopshero_app.organization')),
            ],
            options={
                'verbose_name': 'AWS Account',
                'verbose_name_plural': 'AWS Accounts',
                'ordering': ['-created_at'],
            },
        ),
    ]
