# Generated by Django 6.0 on 2026-01-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0002_make_deployment_environment_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('building', 'Building Image'), ('pushing', 'Pushing to ECR'), ('deploying', 'Deploying Infrastructure'), ('starting', 'Starting Service'), ('running', 'Running'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('teardown_pending', 'Teardown Pending'), ('tearing_down', 'Tearing Down'), ('torn_down', 'Torn Down')], default='pending', max_length=20),
        ),
    ]
