# Generated by Django 6.0 on 2025-12-26 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0003_add_aws_account'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='awsaccount',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_aws_account_name_per_org'),
        ),
    ]
