# Generated by Django 6.0 on 2026-01-28 03:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0003_add_teardown_deployment_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistSignup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source', models.CharField(blank=True, help_text='Where on the landing page they signed up (hero, cta)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Waitlist Signup',
                'verbose_name_plural': 'Waitlist Signups',
                'ordering': ['-created_at'],
            },
        ),
    ]
