# Generated by Django 6.0 on 2025-12-28 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0004_unique_aws_account_name_per_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_organization',
            field=models.ForeignKey(blank=True, help_text='The organization the user is currently working in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='devopshero_app.organization'),
        ),
    ]
