# Generated by Django 6.0 on 2026-01-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0005_add_context_aws_account_to_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('markdown', 'Markdown'), ('code', 'Code Block'), ('progress', 'Progress Indicator'), ('choice', 'Interactive Choice'), ('deployment_log', 'Deployment Log'), ('error', 'Error'), ('tool_call', 'Tool Call'), ('system_trigger', 'System Trigger')], max_length=20),
        ),
    ]
