# Generated by Django 6.0 on 2026-01-10 02:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0006_make_current_organization_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Conversation title (placeholder for now)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='devopshero_app.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Datastore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('engine', models.CharField(choices=[('aurora-mysql', 'Aurora MySQL'), ('aurora-postgresql', 'Aurora PostgreSQL')], max_length=50)),
                ('engine_version', models.CharField(blank=True, help_text='Engine version (uses default if blank)', max_length=50)),
                ('deployment_mode', models.CharField(choices=[('aurora_serverless_v2', 'Aurora Serverless v2'), ('aurora_provisioned', 'Aurora Provisioned')], max_length=50)),
                ('serverless_min_acu', models.FloatField(blank=True, help_text='Minimum ACUs for serverless mode', null=True)),
                ('serverless_max_acu', models.FloatField(blank=True, help_text='Maximum ACUs for serverless mode', null=True)),
                ('provisioned_instance_class', models.CharField(blank=True, help_text='Instance class for provisioned mode', max_length=50)),
                ('database_name', models.CharField(max_length=255)),
                ('storage_encrypted', models.BooleanField(default=True)),
                ('deletion_protection', models.BooleanField(default=False)),
                ('backup_retention_days', models.IntegerField(default=7)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('creating', 'Creating'), ('available', 'Available'), ('error', 'Error'), ('deleting', 'Deleting')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('cluster_arn', models.CharField(blank=True, max_length=2048)),
                ('cluster_endpoint', models.CharField(blank=True, max_length=255)),
                ('credentials_secret_arn', models.CharField(blank=True, max_length=2048)),
                ('connection_secret_arn', models.CharField(blank=True, max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_datastores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('app_type', models.CharField(choices=[('web', 'Web Service'), ('worker', 'Background Worker'), ('scheduled', 'Scheduled Job')], max_length=20)),
                ('build_strategy', models.CharField(choices=[('dockerfile', 'Dockerfile'), ('nixpacks', 'Nixpacks (auto-detect)'), ('buildpack', 'Cloud Native Buildpack')], max_length=20)),
                ('repo_url', models.URLField(help_text='Repository URL (only file:// URLs supported in v1)', max_length=2048)),
                ('branch', models.CharField(max_length=255)),
                ('dockerfile_path', models.CharField(blank=True, help_text='Path to Dockerfile if using dockerfile build strategy', max_length=500)),
                ('container_port', models.IntegerField()),
                ('cpu', models.IntegerField(help_text='Fargate CPU units (256, 512, 1024, etc.)')),
                ('memory', models.IntegerField(help_text='Fargate memory in MiB')),
                ('health_check_path', models.CharField(max_length=255)),
                ('health_check_command', models.CharField(blank=True, help_text='Health check command for non-HTTP health checks', max_length=500)),
                ('environment_variables', models.JSONField(default=list, help_text='List of {name, value} environment variable objects')),
                ('domain_name', models.CharField(blank=True, help_text='Custom domain name for this app', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_apps', to=settings.AUTH_USER_MODEL)),
                ('datastore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to='devopshero_app.datastore')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('git_ref', models.CharField(help_text='Branch, tag, or commit SHA', max_length=255)),
                ('git_commit_sha', models.CharField(blank=True, help_text='Resolved commit SHA', max_length=40)),
                ('git_commit_message', models.CharField(blank=True, max_length=500)),
                ('image_tag', models.CharField(max_length=255)),
                ('image_uri', models.CharField(blank=True, help_text='Full ECR image URI (set after push)', max_length=2048)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building Image'), ('pushing', 'Pushing to ECR'), ('deploying', 'Deploying Infrastructure'), ('starting', 'Starting Service'), ('running', 'Running'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('service_url', models.URLField(blank=True, help_text='URL where the deployed service is accessible', max_length=2048)),
                ('alb_dns', models.CharField(blank=True, help_text='ALB DNS name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='devopshero_app.app')),
                ('conversation', models.ForeignKey(blank=True, help_text='The conversation that triggered this deployment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='devopshero_app.conversation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deployments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('init', 'Initialization'), ('build', 'Docker Build'), ('push', 'ECR Push'), ('synth', 'CDK Synthesis'), ('deploy', 'CDK Deploy'), ('health', 'Health Check'), ('complete', 'Completion')], max_length=20)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, help_text='Structured data: stack name, resource ARN, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devopshero_app.deployment')),
            ],
            options={
                'verbose_name': 'Deployment Log',
                'verbose_name_plural': 'Deployment Logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('system', 'System')], max_length=20)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('markdown', 'Markdown'), ('code', 'Code Block'), ('progress', 'Progress Indicator'), ('choice', 'Interactive Choice'), ('deployment_log', 'Deployment Log'), ('error', 'Error')], max_length=20)),
                ('content', models.TextField(help_text='Message content (JSON for structured types, plain text for text/markdown)')),
                ('metadata', models.JSONField(default=dict, help_text='Extra data: code language, choice options, log level, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='devopshero_app.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('primary_repo_url', models.URLField(blank=True, help_text='Primary repository URL (only file:// URLs supported in v1)', max_length=2048)),
                ('aws_region', models.CharField(help_text='Target AWS region for deployments (e.g., us-east-1)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workspaces', to='devopshero_app.awsaccount')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspaces', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='devopshero_app.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='datastore',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastores', to='devopshero_app.workspace'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Set once workspace is determined during conversation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='devopshero_app.workspace'),
        ),
        migrations.AddField(
            model_name='app',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='devopshero_app.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='datastore',
            unique_together={('workspace', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='app',
            unique_together={('workspace', 'slug')},
        ),
    ]
