# Generated by Django 6.0 on 2026-01-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0007_conversation_datastore_app_deployment_deploymentlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('markdown', 'Markdown'), ('code', 'Code Block'), ('progress', 'Progress Indicator'), ('choice', 'Interactive Choice'), ('deployment_log', 'Deployment Log'), ('error', 'Error'), ('tool_call', 'Tool Call')], max_length=20),
        ),
    ]
