# Generated by Django 6.0 on 2026-01-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0007_add_conversation_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='subdomain',
            field=models.CharField(blank=True, help_text='Route53 subdomain. Defaults to app slug, auto-suffixed with -env if conflict.', max_length=63),
        ),
    ]
