# Generated by Django 6.0 on 2026-01-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0008_add_tool_call_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='repo_url',
        ),
        migrations.AlterField(
            model_name='workspace',
            name='primary_repo_url',
            field=models.URLField(help_text='Primary repository URL (only file:// URLs supported in v1)', max_length=2048),
        ),
    ]
