# Generated by Django 6.0 on 2026-02-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0008_add_subdomain_to_deployment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('ready', 'Ready'), ('error', 'Error'), ('teardown_pending', 'Teardown Pending'), ('tearing_down', 'Tearing Down')], default='pending', max_length=20),
        ),
    ]
