# Generated by Django 6.0 on 2026-01-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0009_remove_app_repo_url_require_workspace_primary_repo'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='session_id',
            field=models.CharField(blank=True, help_text='Claude Agent SDK session ID for conversation continuity', max_length=255, null=True),
        ),
    ]
