# Generated by Django 6.0 on 2026-01-17 23:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0010_add_conversation_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('vpc_stack_name', models.CharField(blank=True, help_text='CloudFormation stack name for VPC', max_length=255)),
                ('cluster_stack_name', models.CharField(blank=True, help_text='CloudFormation stack name for ECS cluster', max_length=255)),
                ('vpc_id', models.CharField(blank=True, help_text='VPC ID after provisioning', max_length=255)),
                ('cluster_arn', models.CharField(blank=True, help_text='ECS cluster ARN after provisioning', max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='devopshero_app.awsaccount')),
            ],
            options={
                'verbose_name': 'Environment',
                'verbose_name_plural': 'Environments',
                'ordering': ['name'],
                'unique_together': {('aws_account', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='deployment',
            name='environment',
            field=models.ForeignKey(blank=True, help_text='The environment this deployment targets', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='devopshero_app.environment'),
        ),
    ]
