# Generated by Django 6.0 on 2026-01-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0011_add_environment_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deployment',
            name='conversation',
        ),
        migrations.AddField(
            model_name='conversation',
            name='deployments',
            field=models.ManyToManyField(blank=True, help_text='Deployments triggered from this conversation', related_name='conversations', to='devopshero_app.deployment'),
        ),
    ]
