# Generated by Django 6.0 on 2026-02-18 03:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0012_rename_running_to_deployed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='mode',
            field=models.CharField(choices=[('general', 'General'), ('environment_setup', 'Environment Setup'), ('app_deployment', 'App Deployment'), ('permissions', 'Permissions')], default='general', help_text='Conversation mode determines system prompt and model selection', max_length=20),
        ),
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('statements', models.JSONField(default=list, help_text='List of policy statement dicts')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved_pending_apply', 'Approved - Pending Apply'), ('applying', 'Applying'), ('applied', 'Applied'), ('failed', 'Failed')], default='draft', max_length=30)),
                ('status_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='devopshero_app.app')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_requests', to='devopshero_app.conversation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permission_requests', to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='devopshero_app.environment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
