# Generated by Django 6.0 on 2026-01-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0012_conversation_deployment_m2m'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='app',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='app',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
