# Generated by Django 6.0 on 2026-01-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0013_globally_unique_app_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_secrets',
            field=models.JSONField(blank=True, help_text='Dict mapping secret field names to values. Use null value to auto-generate.', null=True),
        ),
    ]
