# Generated by Django 6.0 on 2026-01-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devopshero_app", "0014_app_app_secrets"),
    ]

    operations = [
        migrations.AddField(
            model_name="deploymentlog",
            name="source",
            field=models.CharField(
                choices=[
                    ("app", "App"),
                    ("cdk", "CDK"),
                    ("docker", "Docker"),
                    ("system", "System"),
                ],
                default="app",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="deploymentlog",
            name="phase",
        ),
    ]
