# Generated by Django 6.0 on 2026-02-19 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0015_rename_permissionrequest_apppermissionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppermissionrequest',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_permission_requests', to='devopshero_app.app'),
        ),
        migrations.AlterField(
            model_name='apppermissionrequest',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_permission_requests', to='devopshero_app.conversation'),
        ),
        migrations.AlterField(
            model_name='apppermissionrequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_permission_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apppermissionrequest',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_permission_requests', to='devopshero_app.environment'),
        ),
    ]
