# Generated by Django 6.0 on 2026-01-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0015_deploymentlog_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploymentlog',
            name='level',
            field=models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('error', 'Error')], max_length=20),
        ),
    ]
