# Generated by Django 6.0 on 2026-01-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0017_app_org_unique_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='shared_alb_hosted_zone',
            field=models.CharField(blank=True, help_text="Hosted zone for shared ALB wildcard cert (e.g., 'dev.example.com'). Empty = HTTP only.", max_length=255),
        ),
    ]
