# Generated by Django 6.0 on 2026-02-23 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0017_apppermissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apppermissionrequest',
            name='conversation',
        ),
        migrations.AddField(
            model_name='conversation',
            name='context_app_permission_request',
            field=models.ForeignKey(blank=True, help_text='AppPermissionRequest context for permissions-mode conversations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='devopshero_app.apppermissionrequest'),
        ),
    ]
