# Generated by Django 6.0 on 2026-01-22 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0018_add_shared_alb_hosted_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='domain_name',
        ),
    ]
