# Generated by Django 6.0 on 2026-02-27 04:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0019_add_description_to_apppermissionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='devopshero_app.organization')),
            ],
            options={
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GroupAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='devopshero_app.group')),
            ],
            options={
                'unique_together': {('group', 'key', 'value')},
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='devopshero_app.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='IdentityAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_attributes', to='devopshero_app.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_attributes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organization', 'user', 'key', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('workspace', 'Workspace'), ('environment', 'Environment'), ('app', 'App')], max_length=20)),
                ('identity_conditions', models.JSONField(default=list, help_text='List of {"key": "...", "value": "..."} dicts, AND-ed. [{"key": "*", "value": "*"}] for wildcard.')),
                ('resource_conditions', models.JSONField(default=list, help_text='List of {"key": "...", "value": "..."} dicts, AND-ed. [{"key": "*", "value": "*"}] for wildcard.')),
                ('actions', models.JSONField(default=list, help_text='List of action strings. Prefix with "!" for deny.')),
                ('is_system', models.BooleanField(default=False, help_text='Display-only flag for seed policies')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='devopshero_app.organization')),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ResourceTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(choices=[('workspace', 'Workspace'), ('environment', 'Environment'), ('app', 'App')], max_length=20)),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='devopshero_app.app')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='devopshero_app.environment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_tags', to='devopshero_app.organization')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='devopshero_app.workspace')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('app__isnull', True), ('environment__isnull', True), ('resource_type', 'workspace'), ('workspace__isnull', False)), models.Q(('app__isnull', True), ('environment__isnull', False), ('resource_type', 'environment'), ('workspace__isnull', True)), models.Q(('app__isnull', False), ('environment__isnull', True), ('resource_type', 'app'), ('workspace__isnull', True)), _connector='OR'), name='resource_tag_exactly_one_fk')],
            },
        ),
    ]
