# Generated by Django 6.0 on 2026-01-22 03:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0019_remove_app_domain_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('system', 'System'), ('cdk', 'CDK')], default='system', max_length=20)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, help_text='Structured data: stack name, resource ARN, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devopshero_app.environment')),
            ],
            options={
                'verbose_name': 'Environment Log',
                'verbose_name_plural': 'Environment Logs',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['environment', 'created_at'], name='devopshero__environ_63df8b_idx')],
            },
        ),
    ]
