# Generated by Django 6.0 on 2026-02-27 04:03

from typing import Any

from django.db import migrations


def bootstrap_existing_orgs(apps: Any, schema_editor: Any) -> None:
    """For each existing Organization, bootstrap ABAC seed data if no policies exist yet."""
    Organization = apps.get_model("devopshero_app", "Organization")
    OrganizationMembership = apps.get_model("devopshero_app", "OrganizationMembership")
    IdentityAttribute = apps.get_model("devopshero_app", "IdentityAttribute")
    Policy = apps.get_model("devopshero_app", "Policy")

    for org in Organization.objects.all():
        # Skip if policies already exist
        if Policy.objects.filter(organization=org).exists():
            continue

        # Find the first admin membership
        admin_membership = OrganizationMembership.objects.filter(
            organization=org, role="admin",
        ).first()
        if not admin_membership:
            continue

        admin_user = admin_membership.user

        # Create org-role=admin attribute
        IdentityAttribute.objects.get_or_create(
            organization=org,
            user=admin_user,
            key="org-role",
            value="admin",
        )

        # Create seed policies
        seed_policies = [
            {
                "name": "Org admins: full workspace access",
                "resource_type": "workspace",
                "actions": ["workspace:admin"],
            },
            {
                "name": "Org admins: full environment access",
                "resource_type": "environment",
                "actions": ["environment:admin"],
            },
            {
                "name": "Org admins: app usage",
                "resource_type": "app",
                "actions": ["app:use"],
            },
        ]

        for seed in seed_policies:
            Policy.objects.get_or_create(
                organization=org,
                name=seed["name"],
                defaults={
                    "resource_type": seed["resource_type"],
                    "identity_conditions": [{"key": "org-role", "value": "admin"}],
                    "resource_conditions": [{"key": "*", "value": "*"}],
                    "actions": seed["actions"],
                    "is_system": True,
                },
            )


def reverse_bootstrap(apps: Any, schema_editor: Any) -> None:
    """Remove seed policies and attributes (best-effort reverse)."""
    Policy = apps.get_model("devopshero_app", "Policy")
    Policy.objects.filter(is_system=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0020_group_groupattribute_groupmembership_and_more'),
    ]

    operations = [
        migrations.RunPython(bootstrap_existing_orgs, reverse_bootstrap),
    ]
