# Generated by Django 6.0 on 2026-02-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0022_seed_member_viewer_policies'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_org_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='viewer', help_text='Org-role automatically assigned to new identities joining this organization', max_length=20),
        ),
    ]
