# Generated by Django 6.0 on 2026-02-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0023_add_default_org_role_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='default_org_role',
            field=models.CharField(default='viewer', help_text='Org-role automatically assigned to new identities joining this organization', max_length=100),
        ),
    ]
