# Generated by Django 6.0 on 2026-03-09 01:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def rename_deployment_statuses(apps, schema_editor):
    Deployment = apps.get_model("devopshero_app", "Deployment")
    Deployment.objects.filter(status="deployed").update(status="succeeded")
    Deployment.objects.filter(status="superseded").update(status="succeeded")


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0027_organization_bootstrap_admin_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='context_app',
            field=models.ForeignKey(blank=True, help_text='App context for deployment-mode conversations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='devopshero_app.app'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('building', 'Building Image'), ('pushing', 'Pushing to ECR'), ('deploying', 'Deploying Infrastructure'), ('starting', 'Starting Service'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('torn_down', 'Torn Down'), ('teardown_pending', 'Teardown Pending'), ('tearing_down', 'Tearing Down')], default='pending', max_length=20),
        ),
        migrations.RunPython(rename_deployment_statuses, migrations.RunPython.noop),
        migrations.CreateModel(
            name='DeploymentBlueprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('deploying', 'Deploying'), ('failed', 'Failed'), ('active', 'Active'), ('discarded', 'Discarded')], default='draft', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('branch', models.CharField(blank=True, help_text='Branch override for this environment. Blank = use Repository.default_branch.', max_length=255)),
                ('cpu', models.IntegerField(help_text='Fargate CPU units (256, 512, 1024, etc.)')),
                ('memory', models.IntegerField(help_text='Fargate memory in MiB')),
                ('environment_variables', models.JSONField(default=list, help_text='List of {name, value} environment variable objects')),
                ('app_secrets', models.JSONField(blank=True, help_text='Dict mapping secret field names to values. Use null value to auto-generate.', null=True)),
                ('subdomain', models.CharField(blank=True, help_text='Route53 subdomain. Defaults to app slug, auto-suffixed with -env if conflict.', max_length=63)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='devopshero_app.app')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_blueprints', to=settings.AUTH_USER_MODEL)),
                ('datastore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blueprints', to='devopshero_app.datastore')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blueprints', to='devopshero_app.environment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='context_deployment_blueprint',
            field=models.ForeignKey(blank=True, help_text='DeploymentBlueprint context for deployment-mode conversations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='devopshero_app.deploymentblueprint'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='blueprint',
            field=models.ForeignKey(blank=True, help_text='The blueprint this deployment applies. Nullable for legacy deployments.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='devopshero_app.deploymentblueprint'),
        ),
    ]
