# Generated by Django 6.0 on 2026-03-09 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0029_drop_app_runtime_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='blueprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='devopshero_app.deploymentblueprint'),
        ),
    ]
