# Generated by Django 6.0 on 2026-03-09 16:24

from typing import Any

from django.db import migrations
from django.utils import timezone

DEFAULT_BLUEPRINT_CPU = 256
DEFAULT_BLUEPRINT_MEMORY = 512
LEGACY_DEPLOYMENT_STATUSES_TO_FAIL = {
    "pending",
    "building",
    "pushing",
    "deploying",
    "starting",
    "teardown_pending",
    "tearing_down",
}


def _build_backfilled_blueprint_status(deployment_status: str) -> str:
    """Return a closed blueprint state for a backfilled legacy deployment."""
    if deployment_status == "succeeded":
        return "active"
    return "discarded"


def backfill_legacy_deployment_blueprints(apps: Any, schema_editor: Any) -> None:
    """Create placeholder blueprints for legacy deployments before enforcing the foreign key."""
    Deployment = apps.get_model("devopshero_app", "Deployment")
    DeploymentBlueprint = apps.get_model("devopshero_app", "DeploymentBlueprint")
    failure_completed_at = timezone.now()

    legacy_deployments = Deployment.objects.filter(blueprint__isnull=True).order_by("created_at")
    for deployment in legacy_deployments.iterator():
        if deployment.status in LEGACY_DEPLOYMENT_STATUSES_TO_FAIL:
            deployment.status = "failed"
            deployment.status_message = (
                "Marked failed during deployment blueprint backfill. "
                "Re-run the deployment or teardown from the UI."
            )
            if not deployment.completed_at:
                deployment.completed_at = failure_completed_at

        blueprint = DeploymentBlueprint.objects.create(
            app_id=deployment.app_id,
            environment_id=deployment.environment_id,
            status=_build_backfilled_blueprint_status(deployment_status=deployment.status),
            status_message=(
                "Backfilled from legacy deployment. Runtime settings were defaulted to "
                "256 CPU units and 512 MiB memory."
            ),
            branch=deployment.git_ref,
            cpu=DEFAULT_BLUEPRINT_CPU,
            memory=DEFAULT_BLUEPRINT_MEMORY,
            environment_variables=[],
            app_secrets=None,
            datastore_id=None,
            subdomain=deployment.subdomain or "",
            created_by_id=deployment.created_by_id,
        )
        DeploymentBlueprint.objects.filter(id=blueprint.id).update(
            created_at=deployment.created_at,
            updated_at=deployment.updated_at,
        )

        deployment.blueprint_id = blueprint.id
        deployment.save(update_fields=["blueprint", "status", "status_message", "completed_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0029_drop_app_runtime_fields'),
    ]

    operations = [
        migrations.RunPython(backfill_legacy_deployment_blueprints, migrations.RunPython.noop),
    ]
