# Generated by Django 6.0 on 2026-03-11 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0030_blueprint_fk_non_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='context_environment',
            field=models.ForeignKey(blank=True, help_text='Environment context for environment-setup conversations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='devopshero_app.environment'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('provisioning', 'Provisioning'), ('ready', 'Ready'), ('error', 'Error'), ('discarded', 'Discarded'), ('teardown_pending', 'Teardown Pending'), ('tearing_down', 'Tearing Down')], default='pending', max_length=20),
        ),
    ]
