# Generated by Django 6.0 on 2026-04-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0035_add_efs_mount_path_to_apptemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apptemplate',
            name='cdk_stack_profile',
        ),
    ]
