# Generated by Django 6.0 on 2026-04-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0037_replace_efs_mount_path_with_efs_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptemplate',
            name='default_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
