# Generated by Django 6.0 on 2026-04-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0041_appremovaljob'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_removal', 'Pending Removal')], default='active', max_length=20),
        ),
    ]
