# Generated by Django 6.0 on 2026-04-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0042_app_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appremovaljob',
            name='delete_policies',
            field=models.BooleanField(default=False),
        ),
    ]
