# Generated by Codex on 2026-04-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devopshero_app", "0044_multi_container_apptemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="apptemplate",
            name="platform_capabilities",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
