# Generated by Django 6.0 on 2026-05-09 02:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0049_rename_policyproxytoken_to_environmentbearertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserThirdPartyIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google')], max_length=50)),
                ('refresh_token', models.TextField()),
                ('scope', models.TextField(blank=True, help_text='Space-separated scopes granted at auth time (as returned by the provider).')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_party_integrations', to='devopshero_app.environment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_party_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Third-Party Integration',
                'verbose_name_plural': 'User Third-Party Integrations',
                'constraints': [models.UniqueConstraint(fields=('user', 'environment', 'provider'), name='unique_user_env_provider')],
            },
        ),
    ]
