# Generated by Django 6.0 on 2026-05-20 19:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0058_add_github_to_integration_user_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Address the invitation was sent to; the invitee must sign in with this email.', max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Secret bearer token embedded in the invite URL.', unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_sent', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='devopshero_app.organization')),
            ],
            options={
                'verbose_name': 'Organization Invite',
                'verbose_name_plural': 'Organization Invites',
                'ordering': ['-created_at'],
            },
        ),
    ]
