# Generated by Django 6.0 on 2026-05-23 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0059_organizationinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationUserCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('app_slug', models.SlugField(max_length=255)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('telegram', 'Telegram')], max_length=50)),
                ('credentials', models.JSONField(default=dict, help_text='Secret provider-owned values supplied by the user, such as refresh tokens or API keys.')),
                ('config', models.JSONField(default=dict, help_text='Non-secret provider configuration for this logical app.')),
                ('metadata', models.JSONField(default=dict, help_text='Derived display/status data such as bot usernames or granted scopes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Integration User Credential',
                'verbose_name_plural': 'Integration User Credentials',
            },
        ),
        migrations.RemoveConstraint(
            model_name='integrationusergrant',
            name='unique_user_env_provider',
        ),
        migrations.AddField(
            model_name='integrationusercredential',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_credentials', to='devopshero_app.environment'),
        ),
        migrations.AddField(
            model_name='integrationusercredential',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='integrationusergrant',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='integrationusergrant',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='integrationusercredential',
            constraint=models.UniqueConstraint(fields=('owner_user', 'environment', 'app_slug', 'provider'), name='unique_owner_env_appslug_provider'),
        ),
        migrations.DeleteModel(
            name='IntegrationUserGrant',
        ),
    ]
