# Generated by Django 6.0 on 2026-06-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devopshero_app', '0063_alter_integrationusercredential_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationusercredential',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('telegram', 'Telegram'), ('slack', 'Slack'), ('openai-codex', 'OpenAI Codex'), ('openrouter', 'OpenRouter')], max_length=50),
        ),
    ]
