from .landing import landing
from .dashboard import dashboard
from .workspaces import workspaces, workspace_detail, workspace_create, workspace_tag_add, workspace_tag_remove, workspace_tags_save
from .apps import app_detail, app_deployment_teardown, app_deployment_redeploy, app_deployment_status, app_teardown_confirm, app_tag_add, app_tag_remove, app_tags_save
from .environments import environments, environment_detail, environment_tag_add, environment_tag_remove, environment_tags_save
from .environment_editor import (
    environment_editor,
    environment_editor_new,
    environment_editor_environment_section,
    environment_editor_reset,
    environment_editor_reset_new,
)
from .security_hub import security_hub
from .security_permissions_editor import (
    security_permissions_editor,
    security_permissions_editor_apply,
    security_permissions_editor_cancel,
    security_permissions_editor_refresh_resources,
    security_permissions_editor_service_group,
    security_permissions_editor_description,
    security_permissions_editor_update_description,
    security_permissions_editor_update_statement,
    security_permissions_statements,
)
from .settings import (
    settings,
    settings_personal,
    settings_organization,
    settings_aws_accounts,
    settings_aws_accounts_add,
    settings_billing,
    settings_git_integrations,
)
from .partials import random_quote, switch_organization
from .auth import auth_login, auth_callback, auth_logout, oidc_login, oidc_callback, dev_login
from .onboarding import onboarding
from .api import aws_install_account_callback, health_check
from .github import github_connect, github_callback, github_webhook
from .chat import (
    chat_app_deploy,
    chat_list,
    chat_new,
    chat_view,
    chat_send,
    chat_stream,
    chat_messages,
    chat_close,
    chat_fork,
    chat_conversation_title,
    chat_conversation_cost,
)
from .deployment_editor import (
    deployment_editor,
    deployment_editor_new,
    deployment_editor_reset,
    deployment_editor_app_section,
    deployment_editor_blueprint_section,
    deployment_editor_fork,
)
from .waitlist_views import waitlist_signup
from .security_abac import (
    security_people,
    security_people_default_role,
    security_people_detail,
    security_people_attribute_add,
    security_people_attribute_remove,
    security_people_group_add,
    security_people_group_remove,
    security_groups,
    security_group_create,
    security_group_detail,
    security_group_delete,
    security_group_delete_confirm,
    security_group_attribute_add,
    security_group_attribute_remove,
    security_group_member_add,
    security_group_member_remove,
    security_policies,
    security_policy_create,
    security_policy_detail,
    security_policy_delete,
    security_policy_delete_confirm,
)

__all__ = [
    "landing",
    "dashboard",
    "workspaces",
    "workspace_detail",
    "workspace_create",
    "workspace_tag_add",
    "workspace_tag_remove",
    "workspace_tags_save",
    "app_detail",
    "app_deployment_teardown",
    "app_deployment_redeploy",
    "app_deployment_status",
    "app_teardown_confirm",
    "app_tag_add",
    "app_tag_remove",
    "app_tags_save",
    "environments",
    "environment_detail",
    "environment_tag_add",
    "environment_tag_remove",
    "environment_tags_save",
    "environment_editor",
    "environment_editor_new",
    "environment_editor_environment_section",
    "environment_editor_reset",
    "environment_editor_reset_new",
    "security_hub",
    "security_permissions_editor",
    "security_permissions_editor_apply",
    "security_permissions_editor_cancel",
    "security_permissions_editor_refresh_resources",
    "security_permissions_editor_service_group",
    "security_permissions_editor_description",
    "security_permissions_editor_update_description",
    "security_permissions_editor_update_statement",
    "security_permissions_statements",
    "settings",
    "settings_personal",
    "settings_organization",
    "settings_aws_accounts",
    "settings_aws_accounts_add",
    "settings_billing",
    "settings_git_integrations",
    "random_quote",
    "switch_organization",
    "auth_login",
    "auth_callback",
    "auth_logout",
    "oidc_login",
    "oidc_callback",
    "onboarding",
    "aws_install_account_callback",
    "health_check",
    "github_connect",
    "github_callback",
    "github_webhook",
    "chat_app_deploy",
    "chat_list",
    "chat_new",
    "chat_view",
    "chat_send",
    "chat_stream",
    "chat_messages",
    "chat_close",
    "chat_fork",
    "chat_conversation_title",
    "chat_conversation_cost",
    "deployment_editor",
    "deployment_editor_new",
    "deployment_editor_reset",
    "deployment_editor_app_section",
    "deployment_editor_blueprint_section",
    "deployment_editor_fork",
    "waitlist_signup",
    "security_people",
    "security_people_default_role",
    "security_people_detail",
    "security_people_attribute_add",
    "security_people_attribute_remove",
    "security_people_group_add",
    "security_people_group_remove",
    "security_groups",
    "security_group_create",
    "security_group_detail",
    "security_group_delete",
    "security_group_delete_confirm",
    "security_group_attribute_add",
    "security_group_attribute_remove",
    "security_group_member_add",
    "security_group_member_remove",
    "security_policies",
    "security_policy_create",
    "security_policy_detail",
    "security_policy_delete",
    "security_policy_delete_confirm",
]
