version: '3'
services:
  web:
    #image: "elixir:slim"
    #image: "bitwalker/alpine-elixir-phoenix:latest"
    # docker build -t dbp2 .
    image: "dbp2:latest"
    restart: unless-stopped
    build: .
    ports:
      - "443:4343"
    # env_file: ./.aws.env
    environment:
      SSLCERT_MODE: manual
      LE_MODE: production
      RUN_SAMPLER: N
    volumes:
      - ${PWD}/cert/dataengr_coursehero_io.key:/app/lib/db_portal-0.1.0/priv/site_encrypt/certs/dataengr.coursehero.io/privkey.pem
      - ${PWD}/cert/dataengr_coursehero_io.crt:/app/lib/db_portal-0.1.0/priv/site_encrypt/certs/dataengr.coursehero.io/cert.pem
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

    depends_on:
      - db
  shell:
    image: "bitwalker/alpine-elixir-phoenix:latest"
    build: .
    volumes:
      - .:/app
      - ./.mix:/root/.mix
    working_dir: /app
    depends_on:
      - db
    command: ["bash"]

  db:
    image: "mysql:5.7"
    restart: unless-stopped
    volumes:
      - $HOME/big/mysql/dbportal:/var/lib/mysql
    ports:
      - "3306:3306"
    command: ["--bind-address=0.0.0.0", "--skip-name-resolve"]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24

