"""
Django settings for humanityrules_site project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-!@4vjx6%j+tp*4^s(a)93($b!79ky1#$9_xj!p**q-3pc!tw8j")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

# Allow all hosts. In production, CloudFront validates the domain for external traffic.
# In development, there's no security concern for local requests.
ALLOWED_HOSTS = ["*"]

# Trust X-Forwarded-Proto header from ALB (behind CloudFront)
# This makes request.is_secure() return True when the original request was HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

CSRF_TRUSTED_ORIGINS = [
    "https://humanityrules.ngrok.io",
    "https://humanityrules.io",
    "https://*.humanityrules.io"
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "tailwind",
    "tailwindtheme_app",
    "django_browser_reload",
    "django_watchfiles",
    "django_htmx",
    "humanityrules_app",
]

TAILWIND_APP_NAME = "tailwindtheme_app"

# PostHog Analytics Configuration
POSTHOG_API_KEY = os.environ.get("POSTHOG_API_KEY")
POSTHOG_HOST = os.environ.get("POSTHOG_HOST", "https://us.i.posthog.com")
POSTHOG_PROXY_HOST = os.environ.get("POSTHOG_PROXY_HOST")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'servestatic.middleware.ServeStaticMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

if POSTHOG_API_KEY and not DEBUG:
    MIDDLEWARE.append("posthog.integrations.django.PosthogContextMiddleware")

ROOT_URLCONF = 'humanityrules_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'humanityrules_app.context_processors.posthog_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'humanityrules_site.wsgi.application'


# Production: construct DATABASE_URL from individual env vars (injected by ECS from Secrets Manager)
# Local dev: fallback to SQLite
DATABASE_HOST = os.environ.get("DATABASE_HOST")
if DATABASE_HOST:
    # Production: PostgreSQL via individual env vars
    DATABASE_USER = os.environ.get("DATABASE_USERNAME", "")
    DATABASE_PASS = os.environ.get("DATABASE_PASSWORD", "")
    DATABASE_PORT = os.environ.get("DATABASE_PORT", "5432")
    DATABASE_NAME = os.environ.get("DATABASE_NAME", "humr")
    DATABASE_URL = f"postgresql://{DATABASE_USER}:{DATABASE_PASS}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}"
    # Use psycopg3's connection pool instead of CONN_MAX_AGE for ASGI compatibility.
    # Pool is recommended for async Django; CONN_MAX_AGE causes connection leaks in async contexts.
    #
    # Pool sizing: This process runs both the web server and the job worker (background threads
    # for deployments, provisioning, etc.). Default pool is fixed at min_size=4 which is too
    # tight — job worker threads hold connections during long operations (5+ min deployments),
    # leaving few for web requests. Aurora Serverless v2 handles up to 1000 connections, so
    # a generous max_size eliminates pool exhaustion as a failure mode entirely.
    DATABASES = {"default": dj_database_url.parse(DATABASE_URL, conn_max_age=0)}
    DATABASES["default"]["OPTIONS"] = {"pool": {"min_size": 4, "max_size": 200}}
elif os.environ.get("DATABASE_URL"):
    # Alternative: direct DATABASE_URL (e.g., for local PostgreSQL testing)
    DATABASES = {"default": dj_database_url.parse(os.environ["DATABASE_URL"], conn_max_age=0)}
    DATABASES["default"]["OPTIONS"] = {"pool": {"min_size": 4, "max_size": 200}}
else:
    # Local dev: SQLite
    DB_PATH = os.environ.get("HUMR_DB_PATH")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": DB_PATH if DB_PATH else BASE_DIR / "local" / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Custom user model
AUTH_USER_MODEL = 'humanityrules_app.User'

# Login URL for @login_required redirects
LOGIN_URL = '/auth/login/'

# WorkOS Configuration
WORKOS_CLIENT_ID = os.environ.get("WORKOS_CLIENT_ID")
WORKOS_API_KEY = os.environ.get("WORKOS_API_KEY")

# GitHub App Configuration
GITHUB_APP_ID = os.environ.get("GITHUB_APP_ID")
GITHUB_APP_CLIENT_ID = os.environ.get("GITHUB_APP_CLIENT_ID")
GITHUB_APP_CLIENT_SECRET = os.environ.get("GITHUB_APP_CLIENT_SECRET")
GITHUB_APP_PRIVATE_KEY = os.environ.get("GITHUB_APP_PRIVATE_KEY", "").replace("\\n", "\n")
GITHUB_WEBHOOK_SECRET = os.environ.get("GITHUB_WEBHOOK_SECRET")

# HumanityRules API Configuration
HUMR_API_SECRET_KEY = os.environ.get("HUMR_API_SECRET_KEY")

# Central RS256 keypair for env-SSO session JWTs. The control plane mints session
# tokens here; per-env policy-proxy sidecars verify them via /.well-known/jwks.json.
HUMR_ENV_SESSION_JWT_PRIVATE_KEY = os.environ.get("HUMR_ENV_SESSION_JWT_PRIVATE_KEY", "").replace("\\n", "\n")
HUMR_ENV_SESSION_JWT_KID = os.environ.get("HUMR_ENV_SESSION_JWT_KID")

# Merge.dev Agent Handler — single tenant-wide API key + Tool Pack.
# Stored only on HUMR; never injected into customer-deployed Hermes containers.
MERGE_AGENT_HANDLER_API_KEY = os.environ.get("MERGE_AGENT_HANDLER_API_KEY")
MERGE_TOOL_PACK_ID = os.environ.get("MERGE_TOOL_PACK_ID")

# Telegram manager bot (BotFather "Bot Management Mode"): creates and manages
# per-app bots on behalf of users via t.me/newbot deep links, so they never
# touch a token. Stored only on HUMR; never injected into customer containers.
TELEGRAM_MANAGER_BOT_TOKEN = os.environ.get("TELEGRAM_MANAGER_BOT_TOKEN")
TELEGRAM_MANAGER_BOT_USERNAME = os.environ.get("TELEGRAM_MANAGER_BOT_USERNAME")

# HumanityRules AWS Control Plane Credentials (for assuming roles in customer accounts)
HUMR_AWS_ACCESS_KEY = os.environ.get("HUMR_AWS_ACCESS_KEY")
HUMR_AWS_SECRET_KEY = os.environ.get("HUMR_AWS_SECRET_KEY")

# Job Worker - enable with HUMR_RUN_JOB_WORKER=1
HUMR_RUN_JOB_WORKER = os.environ.get("HUMR_RUN_JOB_WORKER") == "1"

# Local-only debug deployment mode - simulated success after ~10 seconds with no repo clone or AWS calls
HUMR_DEBUG_DEPLOYMENTS = DEBUG and os.environ.get("HUMR_DEBUG_DEPLOYMENTS") == "1"

# Claude Agent Configuration
# Priority: ANTHROPIC_API_KEY > AWS_BEDROCK_REGION
# Bedrock credentials: AWS_BEDROCK_ACCESS_KEY_ID + AWS_BEDROCK_SECRET_ACCESS_KEY (optional, falls back to boto3 chain)
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY")
AWS_BEDROCK_REGION = os.environ.get("AWS_BEDROCK_REGION")
AWS_BEDROCK_ACCESS_KEY_ID = os.environ.get("AWS_BEDROCK_ACCESS_KEY_ID")
AWS_BEDROCK_SECRET_ACCESS_KEY = os.environ.get("AWS_BEDROCK_SECRET_ACCESS_KEY")

# Claude model aliases per conversation mode (opus-4.6, sonnet-4.6, opus-4.5, sonnet-4.5, haiku-4.5)
CLAUDE_MODEL_GENERAL = os.environ.get("CLAUDE_MODEL_GENERAL", "sonnet-4.6")
CLAUDE_MODEL_ENVIRONMENT = os.environ.get("CLAUDE_MODEL_ENVIRONMENT", "sonnet-4.6")
CLAUDE_MODEL_APP_DEPLOYMENT = os.environ.get("CLAUDE_MODEL_APP_DEPLOYMENT", "sonnet-4.6")

# Claude Agent Sandbox: Base directory for agent sandbox (cloned repos, temp files, etc.)
CLAUDE_SANDBOX_DIR = BASE_DIR / "local" / "sandbox"

# App Templates: bundled template repositories
TEMPLATE_REPOS_DIR = BASE_DIR / "template_repos"
SANITIZE_SANDBOX_PATHS = True

def posthog_request_filter(request):
    """Skip PostHog tracking for admin, health checks, and static files."""
    skip_prefixes = ('/admin', '/health', '/static', '/__reload__')
    return not request.path.startswith(skip_prefixes)


POSTHOG_MW_REQUEST_FILTER = posthog_request_filter

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}][{levelname}] {message}",
            "style": "{",
            "datefmt": "%d-%m %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "humanityrules_app": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
