"""
Django settings for devopshero_site project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!@4vjx6%j+tp*4^s(a)93($b!79ky1#$9_xj!p**q-3pc!tw8j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'devopshero.ngrok.io']

CSRF_TRUSTED_ORIGINS = ['https://devopshero.ngrok.io']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "tailwind",
    "tailwindtheme_app",
    "django_browser_reload",
    "django_watchfiles",
    "django_htmx",
    "devopshero_app",
]

TAILWIND_APP_NAME = "tailwindtheme_app"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'servestatic.middleware.ServeStaticMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

ROOT_URLCONF = 'devopshero_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'devopshero_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DB_PATH = os.environ.get("DOH_DB_PATH")

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DB_PATH if DB_PATH else BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Custom user model
AUTH_USER_MODEL = 'devopshero_app.User'

# Login URL for @login_required redirects
LOGIN_URL = '/auth/login/'

# WorkOS Configuration
WORKOS_CLIENT_ID = os.environ.get("WORKOS_CLIENT_ID")
WORKOS_API_KEY = os.environ.get("WORKOS_API_KEY")

# GitHub App Configuration
GITHUB_APP_ID = os.environ.get("GITHUB_APP_ID")
GITHUB_APP_CLIENT_ID = os.environ.get("GITHUB_APP_CLIENT_ID")
GITHUB_APP_CLIENT_SECRET = os.environ.get("GITHUB_APP_CLIENT_SECRET")
GITHUB_APP_PRIVATE_KEY = os.environ.get("GITHUB_APP_PRIVATE_KEY", "").replace("\\n", "\n")
GITHUB_WEBHOOK_SECRET = os.environ.get("GITHUB_WEBHOOK_SECRET")

# DevOpsHero API Configuration
DOH_API_SECRET_KEY = os.environ.get("DOH_API_SECRET_KEY")

# DevOpsHero AWS Control Plane Credentials (for assuming roles in customer accounts)
DOH_AWS_ACCESS_KEY = os.environ.get("DOH_AWS_ACCESS_KEY")
DOH_AWS_SECRET_KEY = os.environ.get("DOH_AWS_SECRET_KEY")

# Job Worker - enable with DOH_RUN_JOB_WORKER=1
DOH_RUN_JOB_WORKER = os.environ.get("DOH_RUN_JOB_WORKER") == "1"

# Claude Agent Configuration
# Priority: ANTHROPIC_API_KEY > AWS_BEDROCK_REGION
# Bedrock credentials: AWS_BEDROCK_ACCESS_KEY_ID + AWS_BEDROCK_SECRET_ACCESS_KEY (optional, falls back to boto3 chain)
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY")
AWS_BEDROCK_REGION = os.environ.get("AWS_BEDROCK_REGION")
# CLAUDE_MODEL options:
# - us.anthropic.claude-opus-4-5-20251101-v1:0
# - us.anthropic.claude-sonnet-4-5-20250929-v1:0
# - us.anthropic.claude-3-7-sonnet-20250219-v1:0
CLAUDE_MODEL = os.environ.get("CLAUDE_MODEL", "us.anthropic.claude-sonnet-4-5-20250929-v1:0")
AWS_BEDROCK_ACCESS_KEY_ID = os.environ.get("AWS_BEDROCK_ACCESS_KEY_ID")
AWS_BEDROCK_SECRET_ACCESS_KEY = os.environ.get("AWS_BEDROCK_SECRET_ACCESS_KEY")

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}][{levelname}] {message}",
            "style": "{",
            "datefmt": "%d-%m %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "devopshero_app": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
