# Generated by Django 6.0 on 2026-01-22 22:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('workos_user_id', models.CharField(blank=True, help_text='The user ID from WorkOS', max_length=255, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('current_organization', models.ForeignKey(help_text='The organization the user is currently working in', on_delete=django.db.models.deletion.PROTECT, related_name='current_users', to='humanityrules_app.organization')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AWSAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="User-friendly name for this AWS account (e.g., 'Production', 'Staging')", max_length=255)),
                ('aws_account_id', models.CharField(blank=True, help_text='The 12-digit AWS account ID (populated after verification)', max_length=12)),
                ('external_id', models.UUIDField(default=uuid.uuid4, help_text='External ID for secure cross-account AssumeRole')),
                ('role_arn', models.CharField(blank=True, help_text='IAM role ARN that HumanityRules assumes for deployments', max_length=2048)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('error', 'Error')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True, help_text='Additional status information or error details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_aws_accounts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aws_accounts', to='humanityrules_app.organization')),
            ],
            options={
                'verbose_name': 'AWS Account',
                'verbose_name_plural': 'AWS Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Datastore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('engine', models.CharField(choices=[('aurora-mysql', 'Aurora MySQL'), ('aurora-postgresql', 'Aurora PostgreSQL')], max_length=50)),
                ('engine_version', models.CharField(blank=True, help_text='Engine version (uses default if blank)', max_length=50)),
                ('deployment_mode', models.CharField(choices=[('aurora_serverless_v2', 'Aurora Serverless v2'), ('aurora_provisioned', 'Aurora Provisioned')], max_length=50)),
                ('serverless_min_acu', models.FloatField(blank=True, help_text='Minimum ACUs for serverless mode', null=True)),
                ('serverless_max_acu', models.FloatField(blank=True, help_text='Maximum ACUs for serverless mode', null=True)),
                ('provisioned_instance_class', models.CharField(blank=True, help_text='Instance class for provisioned mode', max_length=50)),
                ('database_name', models.CharField(max_length=255)),
                ('storage_encrypted', models.BooleanField(default=True)),
                ('deletion_protection', models.BooleanField(default=False)),
                ('backup_retention_days', models.IntegerField(default=7)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('creating', 'Creating'), ('available', 'Available'), ('error', 'Error'), ('deleting', 'Deleting')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('cluster_arn', models.CharField(blank=True, max_length=2048)),
                ('cluster_endpoint', models.CharField(blank=True, max_length=255)),
                ('credentials_secret_arn', models.CharField(blank=True, max_length=2048)),
                ('connection_secret_arn', models.CharField(blank=True, max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_datastores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('app_type', models.CharField(choices=[('web', 'Web Service'), ('worker', 'Background Worker'), ('scheduled', 'Scheduled Job')], max_length=20)),
                ('build_strategy', models.CharField(choices=[('dockerfile', 'Dockerfile'), ('nixpacks', 'Nixpacks (auto-detect)'), ('buildpack', 'Cloud Native Buildpack')], max_length=20)),
                ('repo_subpath', models.CharField(blank=True, help_text='Subdirectory within repository (for monorepos, optional)', max_length=500)),
                ('branch', models.CharField(max_length=255)),
                ('dockerfile_path', models.CharField(blank=True, help_text='Path to Dockerfile if using dockerfile build strategy', max_length=500)),
                ('container_port', models.IntegerField()),
                ('cpu', models.IntegerField(help_text='Fargate CPU units (256, 512, 1024, etc.)')),
                ('memory', models.IntegerField(help_text='Fargate memory in MiB')),
                ('health_check_path', models.CharField(max_length=255)),
                ('health_check_command', models.CharField(blank=True, help_text='Health check command for non-HTTP health checks', max_length=500)),
                ('environment_variables', models.JSONField(default=list, help_text='List of {name, value} environment variable objects')),
                ('app_secrets', models.JSONField(blank=True, help_text='Dict mapping secret field names to values. Use null value to auto-generate.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_apps', to=settings.AUTH_USER_MODEL)),
                ('datastore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to='humanityrules_app.datastore')),
                ('organization', models.ForeignKey(help_text='Denormalized from workspace for unique constraint on (organization, slug)', on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='humanityrules_app.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('git_ref', models.CharField(help_text='Branch, tag, or commit SHA', max_length=255)),
                ('git_commit_sha', models.CharField(blank=True, help_text='Resolved commit SHA', max_length=40)),
                ('git_commit_message', models.CharField(blank=True, max_length=500)),
                ('image_tag', models.CharField(max_length=255)),
                ('image_uri', models.CharField(blank=True, help_text='Full ECR image URI (set after push)', max_length=2048)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('building', 'Building Image'), ('pushing', 'Pushing to ECR'), ('deploying', 'Deploying Infrastructure'), ('starting', 'Starting Service'), ('running', 'Running'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('service_url', models.URLField(blank=True, help_text='URL where the deployed service is accessible', max_length=2048)),
                ('alb_dns', models.CharField(blank=True, help_text='ALB DNS name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='humanityrules_app.app')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deployments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Conversation title (placeholder for now)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.CharField(blank=True, help_text='Claude Agent SDK session ID for conversation continuity', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
                ('deployments', models.ManyToManyField(blank=True, help_text='Deployments triggered from this conversation', related_name='conversations', to='humanityrules_app.deployment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='humanityrules_app.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('app', 'App'), ('cdk', 'CDK'), ('docker', 'Docker'), ('system', 'System')], default='app', max_length=20)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, help_text='Structured data: stack name, resource ARN, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='humanityrules_app.deployment')),
            ],
            options={
                'verbose_name': 'Deployment Log',
                'verbose_name_plural': 'Deployment Logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('aws_region', models.CharField(help_text='AWS region for this environment (e.g., us-east-1)', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('vpc_stack_name', models.CharField(blank=True, help_text='CloudFormation stack name for VPC', max_length=255)),
                ('cluster_stack_name', models.CharField(blank=True, help_text='CloudFormation stack name for ECS cluster', max_length=255)),
                ('vpc_id', models.CharField(blank=True, help_text='VPC ID after provisioning', max_length=255)),
                ('cluster_arn', models.CharField(blank=True, help_text='ECS cluster ARN after provisioning', max_length=2048)),
                ('shared_alb_hosted_zone', models.CharField(blank=True, help_text="Hosted zone for shared ALB wildcard cert (e.g., 'dev.example.com'). Empty = HTTP only.", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aws_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='humanityrules_app.awsaccount')),
            ],
            options={
                'verbose_name': 'Environment',
                'verbose_name_plural': 'Environments',
                'ordering': ['name'],
                'unique_together': {('aws_account', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='deployment',
            name='environment',
            field=models.ForeignKey(blank=True, help_text='The environment this deployment targets', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='humanityrules_app.environment'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('system', 'System')], max_length=20)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('markdown', 'Markdown'), ('code', 'Code Block'), ('progress', 'Progress Indicator'), ('choice', 'Interactive Choice'), ('deployment_log', 'Deployment Log'), ('error', 'Error'), ('tool_call', 'Tool Call')], max_length=20)),
                ('content', models.TextField(help_text='Message content (JSON for structured types, plain text for text/markdown)')),
                ('metadata', models.JSONField(default=dict, help_text='Extra data: code language, choice options, log level, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='humanityrules_app.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='GitProviderIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('error', 'Error')], default='pending', max_length=20)),
                ('installation_id', models.CharField(blank=True, help_text='GitHub App installation ID', max_length=255)),
                ('access_token_encrypted', models.TextField(blank=True, help_text='Encrypted OAuth access token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_integrations', to='humanityrules_app.organization')),
            ],
            options={
                'verbose_name': 'Git Provider Integration',
                'verbose_name_plural': 'Git Provider Integrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='humanityrules_app.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Membership',
                'verbose_name_plural': 'Organization Memberships',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('local', 'Local')], max_length=20)),
                ('external_id', models.CharField(blank=True, help_text="Provider's repository ID", max_length=255)),
                ('name', models.CharField(help_text="Repository name (e.g., 'flask-api')", max_length=255)),
                ('full_name', models.CharField(help_text="Full repository name (e.g., 'acme/flask-api')", max_length=500)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('clone_url', models.URLField(help_text='HTTPS clone URL or file:// for local repos', max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(blank=True, help_text='Git provider integration (null for local repos)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repositories', to='humanityrules_app.gitproviderintegration')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='humanityrules_app.organization')),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='context_repository',
            field=models.ForeignKey(blank=True, help_text='Repository context for this conversation (set via UI)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='humanityrules_app.repository'),
        ),
        migrations.AddField(
            model_name='app',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apps', to='humanityrules_app.repository'),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workspaces', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='humanityrules_app.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='datastore',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datastores', to='humanityrules_app.workspace'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='context_workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace context for this conversation (set via UI)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='humanityrules_app.workspace'),
        ),
        migrations.AddField(
            model_name='app',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='humanityrules_app.workspace'),
        ),
        migrations.CreateModel(
            name='EnvironmentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('system', 'System'), ('cdk', 'CDK')], default='system', max_length=20)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('error', 'Error')], max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, help_text='Structured data: stack name, resource ARN, etc.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='humanityrules_app.environment')),
            ],
            options={
                'verbose_name': 'Environment Log',
                'verbose_name_plural': 'Environment Logs',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['environment', 'created_at'], name='devopshero__environ_63df8b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='awsaccount',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_aws_account_name_per_org'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembership',
            unique_together={('user', 'organization')},
        ),
        migrations.AddConstraint(
            model_name='repository',
            constraint=models.UniqueConstraint(fields=('organization', 'full_name'), name='unique_repo_full_name_per_org'),
        ),
        migrations.AlterUniqueTogether(
            name='workspace',
            unique_together={('organization', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='datastore',
            unique_together={('workspace', 'slug')},
        ),
        migrations.AddConstraint(
            model_name='app',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_app_slug_per_org'),
        ),
    ]
