# Generated by Django 6.0 on 2026-01-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("humanityrules_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deployment",
            name="environment",
            field=models.ForeignKey(
                help_text="The environment this deployment targets",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="deployments",
                to="humanityrules_app.environment",
            ),
        ),
    ]
