# Generated by Django 6.0 on 2026-06-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsaccount',
            name='is_humr_sandbox',
            field=models.BooleanField(default=False, help_text="This row points at HumR's own shared sandbox account. Environments here reuse shared base infra instead of provisioning their own."),
        ),
        migrations.AlterField(
            model_name='awsaccount',
            name='role_arn',
            field=models.CharField(blank=True, help_text='IAM role ARN that Humanity Rules assumes for deployments', max_length=2048),
        ),
    ]
