# Generated by Django 6.0 on 2026-06-22 21:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0002_awsaccount_is_humr_sandbox_alter_awsaccount_role_arn'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSharedCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('telegram', 'Telegram'), ('slack', 'Slack'), ('openai-codex', 'OpenAI Codex'), ('openrouter', 'OpenRouter'), ('nous', 'Nous Portal'), ('openai-api', 'OpenAI API'), ('anthropic', 'Anthropic'), ('x', 'X'), ('browseruse', 'Browser Use')], max_length=50)),
                ('scope', models.CharField(choices=[('everyone', 'Everyone'), ('user', 'User'), ('workspace', 'Workspace')], max_length=20)),
                ('credentials', models.JSONField(default=dict, help_text='Secret provider-owned values supplied by the administrator, such as API keys.')),
                ('config', models.JSONField(default=dict, help_text='Non-secret provider configuration.')),
                ('metadata', models.JSONField(default=dict, help_text='Derived display/status data such as validation timestamps.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shared Integration Credential',
                'verbose_name_plural': 'Shared Integration Credentials',
            },
        ),
        migrations.RemoveConstraint(
            model_name='resourcetag',
            name='resource_tag_exactly_one_fk',
        ),
        migrations.AlterField(
            model_name='policy',
            name='resource_type',
            field=models.CharField(choices=[('workspace', 'Workspace'), ('environment', 'Environment'), ('app', 'App'), ('credential', 'Credential')], max_length=20),
        ),
        migrations.AlterField(
            model_name='resourcetag',
            name='resource_type',
            field=models.CharField(choices=[('workspace', 'Workspace'), ('environment', 'Environment'), ('app', 'App'), ('credential', 'Credential')], max_length=20),
        ),
        migrations.AddField(
            model_name='integrationsharedcredential',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The administrator who provisioned this shared credential.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integrationsharedcredential',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_integration_credentials', to='humanityrules_app.organization'),
        ),
        migrations.AddField(
            model_name='integrationsharedcredential',
            name='target_user',
            field=models.ForeignKey(blank=True, help_text='Set only when scope=user; the user whose apps receive this credential.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_shared_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integrationsharedcredential',
            name='target_workspace',
            field=models.ForeignKey(blank=True, help_text='Set only when scope=workspace; the workspace whose apps receive this credential.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_integration_credentials', to='humanityrules_app.workspace'),
        ),
        migrations.AddField(
            model_name='resourcetag',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='humanityrules_app.integrationsharedcredential'),
        ),
        migrations.AddConstraint(
            model_name='resourcetag',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('app__isnull', True), ('credential__isnull', True), ('environment__isnull', True), ('resource_type', 'workspace'), ('workspace__isnull', False)), models.Q(('app__isnull', True), ('credential__isnull', True), ('environment__isnull', False), ('resource_type', 'environment'), ('workspace__isnull', True)), models.Q(('app__isnull', False), ('credential__isnull', True), ('environment__isnull', True), ('resource_type', 'app'), ('workspace__isnull', True)), models.Q(('app__isnull', True), ('credential__isnull', False), ('environment__isnull', True), ('resource_type', 'credential'), ('workspace__isnull', True)), _connector='OR'), name='resource_tag_exactly_one_fk'),
        ),
        migrations.AddConstraint(
            model_name='integrationsharedcredential',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'everyone'), ('target_user__isnull', True), ('target_workspace__isnull', True)), models.Q(('scope', 'user'), ('target_user__isnull', False), ('target_workspace__isnull', True)), models.Q(('scope', 'workspace'), ('target_user__isnull', True), ('target_workspace__isnull', False)), _connector='OR'), name='shared_credential_scope_target_consistent'),
        ),
        migrations.AddConstraint(
            model_name='integrationsharedcredential',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'everyone')), fields=('organization', 'provider'), name='uniq_shared_credential_everyone_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='integrationsharedcredential',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'user')), fields=('organization', 'provider', 'target_user'), name='uniq_shared_credential_user_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='integrationsharedcredential',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'workspace')), fields=('organization', 'provider', 'target_workspace'), name='uniq_shared_credential_workspace_per_provider'),
        ),
    ]
