# Generated by Django 6.0 on 2026-01-30 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0004_waitlistsignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='context_aws_account',
            field=models.ForeignKey(blank=True, help_text='AWS account context for this conversation (set via UI for environment creation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='humanityrules_app.awsaccount'),
        ),
    ]
