# Generated by Django 6.0 on 2026-06-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0004_seed_credential_policies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationsharedcredential',
            options={'verbose_name': 'Integration Shared Credential', 'verbose_name_plural': 'Integration Shared Credentials'},
        ),
    ]
