# Generated by Django 6.0 on 2026-06-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0005_alter_integrationsharedcredential_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsharedcredential',
            name='config',
            field=models.JSONField(blank=True, default=dict, help_text='Non-secret provider configuration.'),
        ),
        migrations.AlterField(
            model_name='integrationsharedcredential',
            name='credentials',
            field=models.JSONField(blank=True, default=dict, help_text='Secret provider-owned values supplied by the administrator, such as API keys.'),
        ),
        migrations.AlterField(
            model_name='integrationsharedcredential',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Derived display/status data such as validation timestamps.'),
        ),
    ]
