# Generated by Django 6.0 on 2026-01-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0006_add_system_trigger_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='mode',
            field=models.CharField(choices=[('general', 'General'), ('environment_setup', 'Environment Setup'), ('app_deployment', 'App Deployment')], default='general', help_text='Conversation mode determines system prompt and model selection', max_length=20),
        ),
    ]
