# Generated by Django 6.0 on 2026-06-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0007_rename_shared_credential_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsharedcredential',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('telegram', 'Telegram'), ('slack', 'Slack'), ('openai-codex', 'OpenAI Codex'), ('openrouter', 'OpenRouter'), ('nous', 'Nous Portal'), ('openai-api', 'OpenAI API'), ('anthropic', 'Anthropic'), ('x', 'X'), ('browseruse', 'Browser Use'), ('tavily', 'Tavily')], max_length=50),
        ),
        migrations.AlterField(
            model_name='integrationusercredential',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('telegram', 'Telegram'), ('slack', 'Slack'), ('openai-codex', 'OpenAI Codex'), ('openrouter', 'OpenRouter'), ('nous', 'Nous Portal'), ('openai-api', 'OpenAI API'), ('anthropic', 'Anthropic'), ('x', 'X'), ('browseruse', 'Browser Use'), ('tavily', 'Tavily')], max_length=50),
        ),
    ]
