# Generated by Django 6.0 on 2026-06-29 01:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0008_alter_integrationsharedcredential_provider_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSharedCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('telegram', 'Telegram'), ('slack', 'Slack'), ('openai-codex', 'OpenAI Codex'), ('openrouter', 'OpenRouter'), ('nous', 'Nous Portal'), ('openai-api', 'OpenAI API'), ('anthropic', 'Anthropic'), ('x', 'X'), ('browseruse', 'Browser Use'), ('tavily', 'Tavily')], max_length=50)),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='Secret provider-owned values supplied by HumR staff, such as API keys.')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Non-secret provider configuration.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Derived display/status data such as validation timestamps.')),
                ('enabled', models.BooleanField(default=True, help_text='When false the share is inert — kept for history without being handed to brokers.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='The HumR staff member who provisioned this platform credential.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Shared Credential',
                'verbose_name_plural': 'Platform Shared Credentials',
                'constraints': [models.UniqueConstraint(condition=models.Q(('enabled', True)), fields=('provider',), name='uniq_enabled_platform_credential_per_provider')],
            },
        ),
    ]
