# Generated by Django 6.0 on 2026-02-05 20:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0009_add_environment_teardown_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('building', 'Building Image'), ('pushing', 'Pushing to ECR'), ('deploying', 'Deploying Infrastructure'), ('starting', 'Starting Service'), ('running', 'Running'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('teardown_pending', 'Teardown Pending'), ('tearing_down', 'Tearing Down')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='LLMUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('agent_turn', 'Agent Turn'), ('title_generation', 'Title Generation')], max_length=20)),
                ('model_alias', models.CharField(help_text="Model alias used (e.g., 'opus-4.6', 'haiku-4.5')", max_length=50)),
                ('model_id', models.CharField(help_text='Resolved API or Bedrock model ID', max_length=255)),
                ('input_tokens', models.IntegerField(help_text='Number of input tokens consumed', null=True)),
                ('output_tokens', models.IntegerField(help_text='Number of output tokens generated', null=True)),
                ('cost_usd', models.DecimalField(decimal_places=6, help_text='Cost in USD (from SDK or computed)', max_digits=10, null=True)),
                ('duration_ms', models.IntegerField(help_text='Wall-clock duration in milliseconds', null=True)),
                ('num_turns', models.IntegerField(help_text='Number of agent turns (only for agent_turn source)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage_logs', to='humanityrules_app.conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_usage_logs', to='humanityrules_app.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM Usage Log',
                'verbose_name_plural': 'LLM Usage Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='devopshero__organiz_efe97b_idx'), models.Index(fields=['conversation', 'created_at'], name='devopshero__convers_2a79a1_idx')],
            },
        ),
    ]
