# Generated by Django 6.0 on 2026-06-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0009_platformsharedcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationsharedcredential',
            name='token_cache',
            field=models.JSONField(blank=True, default=dict, help_text='Control-plane cache of the last exchanged access token for OAuth shares: {secrets, expires_at}.'),
        ),
        migrations.AddField(
            model_name='platformsharedcredential',
            name='token_cache',
            field=models.JSONField(blank=True, default=dict, help_text='Control-plane cache of the last exchanged access token for OAuth shares: {secrets, expires_at}.'),
        ),
    ]
