# Generated by Django 6.0 on 2026-06-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0010_integrationsharedcredential_token_cache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='llm_preset',
            field=models.CharField(choices=[('bedrock', 'Bedrock'), ('codex', 'OpenAI Codex')], default='codex', help_text='LLM preset for personal assistants deployed by this org. Defaults to Codex; set to Bedrock per-customer in admin for the demo.', max_length=32),
        ),
    ]
