# Generated by Django 6.0 on 2026-06-30 17:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0011_organization_llm_preset'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxSlugClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_slug_claims', to='humanityrules_app.organization')),
            ],
        ),
    ]
