# Generated by Django 6.0 on 2026-07-09 23:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0012_sandboxslugclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppEnvironmentActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('last_policy_proxy_activity_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_activities', to='humanityrules_app.app')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_activities', to='humanityrules_app.environment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_environment_activities', to='humanityrules_app.organization')),
            ],
            options={
                'verbose_name': 'App Environment Activity',
                'verbose_name_plural': 'App Environment Activities',
                'indexes': [models.Index(fields=['organization', 'last_policy_proxy_activity_at'], name='humanityrul_organiz_6fa19e_idx')],
                'constraints': [models.UniqueConstraint(fields=('app', 'environment'), name='unique_app_environment_activity')],
            },
        ),
    ]
