# Generated by Django 6.0 on 2026-02-19 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0013_alter_conversation_mode_permissionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwsResourceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('resources', models.JSONField(default=list, help_text='List of {arn, label} dicts')),
                ('fetched_at', models.DateTimeField()),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_caches', to='humanityrules_app.environment')),
            ],
            options={
                'unique_together': {('environment', 'service')},
            },
        ),
    ]
