# Generated by Django 6.0 on 2026-02-19 23:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0016_rename_apppermissionrequest_related_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermissions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('statements', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to='humanityrules_app.app')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_permissions', to='humanityrules_app.environment')),
            ],
            options={
                'unique_together': {('app', 'environment')},
            },
        ),
    ]
