# Generated by Django 6.0 on 2026-07-15 01:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0017_hermes_llm_preset_environment'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebappPublicGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('slug', models.CharField(help_text="Webapp hostname prefix, e.g. 'dashboard' in dashboard-<agent-host>.", max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null = public until revoked.', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webapp_public_grants', to='humanityrules_app.app')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webapp_public_grants', to='humanityrules_app.environment')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webapp_grants_created', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webapp_grants_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webapp Public Grant',
                'verbose_name_plural': 'Webapp Public Grants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app', 'environment', 'slug'], name='humanityrul_app_id_8f1b46_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('app', 'environment', 'slug'), name='unique_unrevoked_webapp_grant')],
            },
        ),
    ]
