# Generated by Django 6.0 on 2026-07-18 19:54

import humanityrules_app.app_slugs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0018_webapppublicgrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='slug',
            field=models.SlugField(help_text='Hostname label containing lowercase letters and digits only.', max_length=255, validators=[humanityrules_app.app_slugs.validate_app_hostname_label]),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='subdomain',
            field=models.CharField(blank=True, help_text='Resolved hostname label containing lowercase letters and digits only. Blank defaults to the app slug.', max_length=63, validators=[humanityrules_app.app_slugs.validate_app_hostname_label]),
        ),
        migrations.AlterField(
            model_name='deploymentblueprint',
            name='subdomain',
            field=models.CharField(blank=True, help_text='Hostname label containing lowercase letters and digits only. Blank defaults to the app slug.', max_length=63, validators=[humanityrules_app.app_slugs.validate_app_hostname_label]),
        ),
    ]
