# Generated by Django 6.0 on 2026-02-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0018_remove_apppermissionrequest_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppermissionrequest',
            name='description',
            field=models.TextField(blank=True, help_text='Human/agent-authored rationale for the permission changes'),
        ),
    ]
