# Generated by Django 6.0 on 2026-07-19 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0019_alter_app_slug_alter_deployment_subdomain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apptemplate',
            old_name='enable_subhosting',
            new_name='enable_webapp_hosts',
        ),
    ]
