# Generated by Django 6.0 on 2026-07-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0020_enable_webapp_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='eni_trunking_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
