# Generated by Django 6.0 on 2026-07-20 07:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0021_environment_eni_trunking_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobWorkerRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, help_text='Worker scope label; empty = unscoped main worker', max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('heartbeat_at', models.DateTimeField(help_text='Last proof of life')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='apppermissionrequest',
            name='claimed_by_run',
            field=models.ForeignKey(blank=True, help_text='Worker run that claimed this job; liveness input for stale-job detection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='humanityrules_app.jobworkerrun'),
        ),
        migrations.AddField(
            model_name='appremovaljob',
            name='claimed_by_run',
            field=models.ForeignKey(blank=True, help_text='Worker run that claimed this job; liveness input for stale-job detection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='humanityrules_app.jobworkerrun'),
        ),
        migrations.AddField(
            model_name='costrefreshjob',
            name='claimed_by_run',
            field=models.ForeignKey(blank=True, help_text='Worker run that claimed this job; liveness input for stale-job detection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='humanityrules_app.jobworkerrun'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='claimed_by_run',
            field=models.ForeignKey(blank=True, help_text='Worker run that claimed this job; liveness input for stale-job detection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='humanityrules_app.jobworkerrun'),
        ),
        migrations.AddField(
            model_name='environment',
            name='claimed_by_run',
            field=models.ForeignKey(blank=True, help_text='Worker run that claimed this job; liveness input for stale-job detection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='humanityrules_app.jobworkerrun'),
        ),
    ]
