# Generated by Django 6.0 on 2026-07-20 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0022_jobworkerrun_apppermissionrequest_claimed_by_run_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='context_app',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='context_app_permission_request',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='context_aws_account',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='context_deployment_blueprint',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='context_environment',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='context_repository',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='context_workspace',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='deployments',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.RemoveIndex(
            model_name='llmusagelog',
            name='humanityrul_organiz_03e89d_idx',
        ),
        migrations.RemoveIndex(
            model_name='llmusagelog',
            name='humanityrul_convers_64c1fa_idx',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.RemoveField(
            model_name='llmusagelog',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='llmusagelog',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='llmusagelog',
            name='user',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='LLMUsageLog',
        ),
    ]
