# Generated by Django 6.0 on 2026-07-20 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0023_drop_agent_conversation_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploymentblueprint',
            name='datastore',
        ),
        migrations.RemoveField(
            model_name='apptemplate',
            name='datastore_config',
        ),
        migrations.DeleteModel(
            name='Datastore',
        ),
    ]
