# Generated by Django 6.0 on 2026-03-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0024_remove_choices_from_default_org_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='auth_provider',
            field=models.CharField(choices=[('workos', 'Workos'), ('oidc', 'Oidc')], default='workos', max_length=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='email_domain',
            field=models.CharField(blank=True, help_text="e.g. 'acme.com' — for email-based routing to this org's auth provider", max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='oidc_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='oidc_client_secret',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='organization',
            name='oidc_issuer_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='oidc_sub',
            field=models.CharField(blank=True, help_text='OIDC subject identifier', max_length=255, null=True, unique=True),
        ),
    ]
