# Generated by Django 6.0 on 2026-03-04 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0025_organization_auth_provider_organization_email_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='email_domain',
        ),
    ]
