# Generated by Django 6.0 on 2026-07-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0025_collapse_deployment_blueprint_into_app'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('building', 'Building Image'), ('pushing', 'Pushing to ECR'), ('deploying', 'Deploying'), ('starting', 'Starting'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('torn_down', 'Torn Down'), ('teardown_pending', 'Teardown Pending'), ('tearing_down', 'Tearing Down')], default='pending', max_length=20),
        ),
    ]
