# Generated by Django 6.0 on 2026-07-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0026_remove_deployment_rolled_back_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('deploying', 'Deploying'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('torn_down', 'Torn Down'), ('teardown_pending', 'Teardown Pending'), ('tearing_down', 'Tearing Down')], default='pending', max_length=20),
        ),
    ]
