# Generated by Django 6.0 on 2026-03-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0026_remove_organization_email_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bootstrap_admin_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
