# Generated by Django 6.0 on 2026-07-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0027_simplify_deployment_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='app_type',
        ),
    ]
