# Generated by Django 6.0 on 2026-03-09 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0028_blueprint_refactor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='app_secrets',
        ),
        migrations.RemoveField(
            model_name='app',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='app',
            name='datastore',
        ),
        migrations.RemoveField(
            model_name='app',
            name='environment_variables',
        ),
        migrations.RemoveField(
            model_name='app',
            name='memory',
        ),
    ]
