# Generated by Django 6.0 on 2026-07-22 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0029_collapse_deployment_into_app'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deploymentrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Deployment Record', 'verbose_name_plural': 'Deployment Records'},
        ),
    ]
