# Generated by Django 6.0 on 2026-04-14 02:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0032_alter_deployment_blueprint_non_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji or icon class for template picker UI', max_length=50)),
                ('category', models.CharField(help_text='e.g. ai-assistant, web-app, api', max_length=50)),
                ('source_repo_path', models.CharField(help_text="Relative path within template_repos/, e.g. 'openclaw_agent'", max_length=500)),
                ('app_type', models.CharField(max_length=20)),
                ('build_strategy', models.CharField(max_length=20)),
                ('dockerfile_path', models.CharField(blank=True, max_length=500)),
                ('container_port', models.IntegerField()),
                ('health_check_path', models.CharField(max_length=255)),
                ('health_check_command', models.CharField(blank=True, max_length=500)),
                ('cpu', models.IntegerField()),
                ('memory', models.IntegerField()),
                ('runtime_variables', models.JSONField()),
                ('datastore_config', models.JSONField(blank=True, null=True)),
                ('cdk_stack_profile', models.CharField(help_text='e.g. fargate_web', max_length=50)),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='deploymentblueprint',
            options={'ordering': ['-created_at'], 'verbose_name': 'Deployment Blueprint', 'verbose_name_plural': 'Deployment Blueprints'},
        ),
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('building', 'Building Image'), ('pushing', 'Pushing to ECR'), ('deploying', 'Deploying'), ('starting', 'Starting'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rolled_back', 'Rolled Back'), ('torn_down', 'Torn Down'), ('teardown_pending', 'Teardown Pending'), ('tearing_down', 'Tearing Down')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='app',
            name='source_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployed_apps', to='humanityrules_app.apptemplate'),
        ),
    ]
