# Generated by Django 6.0 on 2026-07-30 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0032_org_platform_capabilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingUsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('app_id', models.UUIDField(help_text="Snapshot of the app's id at ingest; survives app deletion.")),
                ('app_slug', models.CharField(help_text="Snapshot of the app's slug at ingest; survives app deletion.", max_length=255)),
                ('owner_username', models.CharField(max_length=255)),
                ('source', models.CharField(help_text="Billable source key; 'llm' for model-provider usage.", max_length=32)),
                ('subkey', models.CharField(blank=True, help_text='Source-specific sub-dimension (llm: provider model id as observed by the broker).', max_length=255)),
                ('quantities', models.JSONField(help_text="The source's billable units, e.g. llm token buckets. Schema is per source.")),
                ('occurred_at', models.DateTimeField(help_text='Event time at the broker; rating selects the rate card active here.')),
                ('idempotency_key', models.CharField(help_text='Minted by the broker at event creation; duplicate reports are no-ops.', max_length=128, unique=True)),
                ('rated_at', models.DateTimeField(blank=True, help_text='Set once rating has charged this event.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_usage_events', to='humanityrules_app.organization')),
            ],
            options={
                'verbose_name': 'Billing Usage Event',
                'verbose_name_plural': 'Billing Usage Events',
                'indexes': [models.Index(fields=['organization', 'occurred_at'], name='humanityrul_organiz_260a15_idx'), models.Index(condition=models.Q(('rated_at__isnull', True)), fields=['rated_at'], name='billing_usage_unrated_idx')],
            },
        ),
    ]
