# Generated by Django 6.0 on 2026-07-30 23:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0033_billingusageevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('credits', models.DecimalField(decimal_places=0, default=0, help_text="Whole credits remaining; equals the sum of this organization's ledger entries.", max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_balance', to='humanityrules_app.organization')),
            ],
            options={
                'verbose_name': 'Billing Balance',
                'verbose_name_plural': 'Billing Balances',
            },
        ),
        migrations.CreateModel(
            name='BillingLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('grant', 'Grant'), ('charge', 'Charge'), ('adjustment', 'Adjustment'), ('expiry', 'Expiry')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=0, help_text='Signed whole credits: positive for grants, negative for charges and expiry.', max_digits=20)),
                ('idempotency_key', models.CharField(help_text="Per-source key, e.g. 'charge:{org_id}:{app_id}:{date}'. A duplicate insert is a no-op.", max_length=128, unique=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable line for the billing page.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Type-specific facts: grants stamp plan + plan_version, charges rate card versions + usage breakdown.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Equals created_at except on today\'s accumulating day charge — the one mutable row.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_ledger_entries', to='humanityrules_app.organization')),
                ('usage_event', models.ForeignKey(blank=True, help_text='The single metered fact behind this entry; null on day charges, which aggregate many.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='humanityrules_app.billingusageevent')),
            ],
            options={
                'verbose_name': 'Billing Ledger Entry',
                'verbose_name_plural': 'Billing Ledger Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='humanityrul_organiz_e70525_idx')],
            },
        ),
    ]
