# Generated by Django 6.0 on 2026-04-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0033_add_app_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='health_check_grace_period',
            field=models.IntegerField(default=0, help_text='ECS health check grace period in seconds. 0 = use environment default.'),
        ),
        migrations.AddField(
            model_name='apptemplate',
            name='health_check_grace_period',
            field=models.IntegerField(default=0, help_text='ECS health check grace period in seconds. 0 = use environment default.'),
        ),
    ]
