# Generated by Django 6.0 on 2026-04-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0034_add_health_check_grace_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptemplate',
            name='efs_mount_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
