# Generated by Django 6.0 on 2026-08-01 21:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0035_organization_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(max_length=255)),
                ('stripe_subscription_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(help_text="Stripe's subscription status, stored verbatim.", max_length=32)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_subscription', to='humanityrules_app.organization')),
            ],
            options={
                'verbose_name': 'Billing Subscription',
                'verbose_name_plural': 'Billing Subscriptions',
            },
        ),
    ]
