# Generated by Django 6.0 on 2026-08-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0036_billingsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('stripe_event_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=255)),
                ('stripe_created_at', models.DateTimeField()),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stripe Webhook Event',
                'verbose_name_plural': 'Stripe Webhook Events',
            },
        ),
        migrations.AddField(
            model_name='billingsubscription',
            name='cancel_at',
            field=models.DateTimeField(blank=True, help_text='When Stripe will terminate the subscription; set while a cancellation is pending.', null=True),
        ),
        migrations.AddField(
            model_name='billingsubscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, help_text='When the cancellation was requested, not when it takes effect.', null=True),
        ),
        migrations.AddField(
            model_name='billingsubscription',
            name='latest_subscription_event_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
