# Generated by Django 6.0 on 2026-04-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0036_remove_cdk_stack_profile_from_apptemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apptemplate',
            name='efs_mount_path',
        ),
        migrations.AddField(
            model_name='apptemplate',
            name='efs_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
