# Generated by Django 6.0 on 2026-08-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0037_stripewebhookevent_billingsubscription_cancel_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsubscription',
            name='latest_paid_period_start',
            field=models.DateTimeField(blank=True, help_text='Start of the newest period confirmed paid by invoice.paid; never inferred from subscription state.', null=True),
        ),
        migrations.AlterField(
            model_name='billingsubscription',
            name='status',
            field=models.CharField(blank=True, help_text="Stripe's subscription status, stored verbatim; null until a status-bearing event arrives.", max_length=32, null=True),
        ),
    ]
