# Generated by Django 6.0 on 2026-08-18 23:36

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def create_platform_settings(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Create the one platform settings row with public signup disabled."""
    del schema_editor
    platform_settings = apps.get_model(app_label="humanityrules_app", model_name="PlatformSettings")
    platform_settings.objects.create(id=1, public_signup_enabled=False)


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0038_billingsubscription_latest_paid_period_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('public_signup_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
            },
        ),
        migrations.RunPython(
            code=create_platform_settings,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
