# Generated by Django 6.0 on 2026-04-19 06:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0038_apptemplate_default_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyProxyToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(help_text='SHA-256 hex digest of the raw bearer token.', max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('environment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy_proxy_token', to='humanityrules_app.environment')),
            ],
        ),
    ]
