# Generated by Django 6.0 on 2026-04-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0039_add_policy_proxy_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptemplate',
            name='prefill_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
