# Generated by Django 6.0 on 2026-04-21 03:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0040_apptemplate_prefill_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRemovalJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('app_id_snapshot', models.UUIDField()),
                ('app_slug_snapshot', models.SlugField(max_length=255)),
                ('app_name_snapshot', models.CharField(max_length=255)),
                ('workspace_slug_snapshot', models.SlugField(max_length=255)),
                ('delete_secrets', models.BooleanField(default=False)),
                ('delete_efs_data', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_removal_jobs', to='humanityrules_app.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
