# Generated by Django 6.0 on 2026-08-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("humanityrules_app", "0040_contactsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlistsignup",
            name="invitation_sent_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="waitlistsignup",
            name="workos_invitation_id",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="WorkOS application-wide invitation sent to this person.",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
