# Generated by Django 6.0 on 2026-04-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0043_appremovaljob_delete_policies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apptemplate',
            name='app_type',
        ),
        migrations.RemoveField(
            model_name='apptemplate',
            name='build_strategy',
        ),
        migrations.RemoveField(
            model_name='apptemplate',
            name='container_port',
        ),
        migrations.RemoveField(
            model_name='apptemplate',
            name='dockerfile_path',
        ),
        migrations.RemoveField(
            model_name='apptemplate',
            name='health_check_command',
        ),
        migrations.RemoveField(
            model_name='apptemplate',
            name='health_check_grace_period',
        ),
        migrations.RemoveField(
            model_name='apptemplate',
            name='health_check_path',
        ),
        migrations.RemoveField(
            model_name='apptemplate',
            name='runtime_variables',
        ),
        migrations.RemoveField(
            model_name='apptemplate',
            name='source_repo_path',
        ),
        migrations.RemoveField(
            model_name='deploymentblueprint',
            name='app_secrets',
        ),
        migrations.RemoveField(
            model_name='deploymentblueprint',
            name='environment_variables',
        ),
        migrations.AddField(
            model_name='apptemplate',
            name='alb_target_container',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='apptemplate',
            name='containers',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='deploymentblueprint',
            name='containers',
            field=models.JSONField(default=list),
        ),
    ]
