# Generated by Django 6.0 on 2026-08-27 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0044_split_last_attempt_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppBearerToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(help_text='SHA-256 hex digest of the raw bearer token.', max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_bearer_token', to='humanityrules_app.app')),
            ],
        ),
    ]
