# Generated by Django 6.0 on 2026-08-27 07:26
#
# Per-app bearer cutover, final step: the per-environment bearer model goes away
# (every live app must be redeployed to receive its own HUMR_APP_BEARER; see the
# cutover runbook in docs/policy_proxy_design.md), and the template container
# knob that opts a container into the app bearer overlay is renamed
# from `requires_env_bearer` to `requires_app_bearer` inside the
# stored AppTemplate.containers JSON so existing templates keep injecting the
# bearer without a re-seed.

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


OLD_KEY = "requires_env_bearer"
NEW_KEY = "requires_app_bearer"


def _rename_key(containers: list[dict], old: str, new: str) -> list[dict]:
    """Return *containers* with *old* renamed to *new* on every entry that carries it."""
    result: list[dict] = []
    for container in containers or []:
        updated = dict(container)
        if old in updated:
            updated[new] = updated.pop(old)
        result.append(updated)
    return result


def rename_forward(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    del schema_editor
    app_template = apps.get_model("humanityrules_app", "AppTemplate")
    for template in app_template.objects.all().iterator():
        template.containers = _rename_key(containers=list(template.containers or []), old=OLD_KEY, new=NEW_KEY)
        template.save(update_fields=["containers"])


def rename_backward(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    del schema_editor
    app_template = apps.get_model("humanityrules_app", "AppTemplate")
    for template in app_template.objects.all().iterator():
        template.containers = _rename_key(containers=list(template.containers or []), old=NEW_KEY, new=OLD_KEY)
        template.save(update_fields=["containers"])


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0045_appbearertoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvironmentBearerToken',
        ),
        migrations.RunPython(code=rename_forward, reverse_code=rename_backward),
    ]
