# Generated by Django 6.0 on 2026-04-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0045_apptemplate_platform_capabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptemplate',
            name='default_compute_mode',
            field=models.CharField(choices=[('fargate', 'Fargate'), ('ec2', 'EC2 Capacity')], default='fargate', help_text='Default ECS compute backend for deployments created from this template.', max_length=20),
        ),
        migrations.AddField(
            model_name='deploymentblueprint',
            name='compute_mode',
            field=models.CharField(choices=[('fargate', 'Fargate'), ('ec2', 'EC2 Capacity')], default='fargate', help_text='ECS compute backend for this app in this environment.', max_length=20),
        ),
        migrations.AlterField(
            model_name='deploymentblueprint',
            name='cpu',
            field=models.IntegerField(help_text='ECS task CPU units (256, 512, 1024, etc.)'),
        ),
        migrations.AlterField(
            model_name='deploymentblueprint',
            name='memory',
            field=models.IntegerField(help_text='ECS task memory in MiB'),
        ),
    ]
