# Generated by Django 6.0 on 2026-04-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0046_apptemplate_default_compute_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appremovaljob',
            name='teardown_first',
            field=models.BooleanField(default=False),
        ),
    ]
