# Generated by Django 6.0 on 2026-05-10 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0052_rename_gitproviderintegration_to_integrationgitprovider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationconfig',
            options={'verbose_name': 'Integration Config', 'verbose_name_plural': 'Integration Configs'},
        ),
    ]
