# Generated by Django 6.0 on 2026-05-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0055_apptemplate_serialize_task_replacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='label',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
