# Generated by Django 6.0 on 2026-05-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0057_remove_hermes_docker_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationusergrant',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('github', 'GitHub')], max_length=50),
        ),
    ]
