# Generated by Django 6.0 on 2026-05-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0061_apptemplate_enable_subhosting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationusercredential',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('telegram', 'Telegram'), ('slack', 'Slack')], max_length=50),
        ),
    ]
