# Generated by Django 6.0 on 2026-06-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0062_alter_integrationusercredential_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationusercredential',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('github', 'GitHub'), ('telegram', 'Telegram'), ('slack', 'Slack'), ('openai-codex', 'OpenAI Codex')], max_length=50),
        ),
    ]
