# Generated by Django 6.0 on 2026-06-16 02:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0068_add_x_integration_config_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDailyCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(help_text="Cost source key, e.g. 'bedrock'.", max_length=32)),
                ('date', models.DateField(help_text='UTC calendar day this cost is attributed to.')),
                ('subkey', models.CharField(help_text="Source-specific sub-dimension (Bedrock: normalized model id). '' = presence sentinel.", max_length=255)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('details', models.JSONField(default=dict, help_text='Source-specific detail (token counts, flags).')),
                ('is_final', models.BooleanField(default=False, help_text='Frozen: the day has aged past the lag window and is never re-queried.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_costs', to='humanityrules_app.app')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_daily_costs', to='humanityrules_app.environment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_daily_costs', to='humanityrules_app.organization')),
            ],
            options={
                'verbose_name': 'App Daily Cost',
                'verbose_name_plural': 'App Daily Costs',
                'indexes': [models.Index(fields=['app', 'date'], name='devopshero__app_id_d5b13b_idx'), models.Index(fields=['organization', 'date'], name='devopshero__organiz_183fd3_idx')],
                'constraints': [models.UniqueConstraint(fields=('app', 'environment', 'source', 'date', 'subkey'), name='unique_app_daily_cost')],
            },
        ),
        migrations.CreateModel(
            name='CostRefreshJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('status_message', models.TextField(blank=True)),
                ('result', models.JSONField(default=dict, help_text="Recompute summary, e.g. {'rolling_24h_usd': '1.23', 'rolling_24h_by_source': {...}}.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_refresh_jobs', to='humanityrules_app.app')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_refresh_jobs', to='humanityrules_app.organization')),
            ],
            options={
                'verbose_name': 'Cost Refresh Job',
                'verbose_name_plural': 'Cost Refresh Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['app', 'status'], name='devopshero__app_id_e613d4_idx'), models.Index(fields=['status'], name='devopshero__status_970ba9_idx')],
            },
        ),
    ]
