# Generated by Django 6.0 on 2026-06-21 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humanityrules_app', '0070_add_browseruse_integration_provider'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appdailycost',
            new_name='humanityrul_app_id_2c5294_idx',
            old_name='devopshero__app_id_d5b13b_idx',
        ),
        migrations.RenameIndex(
            model_name='appdailycost',
            new_name='humanityrul_organiz_2f4296_idx',
            old_name='devopshero__organiz_183fd3_idx',
        ),
        migrations.RenameIndex(
            model_name='costrefreshjob',
            new_name='humanityrul_app_id_279df5_idx',
            old_name='devopshero__app_id_e613d4_idx',
        ),
        migrations.RenameIndex(
            model_name='costrefreshjob',
            new_name='humanityrul_status_476347_idx',
            old_name='devopshero__status_970ba9_idx',
        ),
        migrations.RenameIndex(
            model_name='environmentlog',
            new_name='humanityrul_environ_b8943b_idx',
            old_name='devopshero__environ_63df8b_idx',
        ),
        migrations.RenameIndex(
            model_name='llmusagelog',
            new_name='humanityrul_organiz_03e89d_idx',
            old_name='devopshero__organiz_efe97b_idx',
        ),
        migrations.RenameIndex(
            model_name='llmusagelog',
            new_name='humanityrul_convers_64c1fa_idx',
            old_name='devopshero__convers_2a79a1_idx',
        ),
    ]
