from django.urls import path
from . import views

urlpatterns = [
    # Health check for ALB/ECS
    path("health/", views.health_check, name="health_check"),

    path("", views.landing, name="landing"),
    path("waitlist/signup/", views.waitlist_signup, name="waitlist_signup"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("workspaces/", views.workspaces, name="workspaces"),
    path("workspaces/create/", views.workspace_create, name="workspace_create"),
    path("workspaces/<slug:workspace_slug>/", views.workspace_detail, name="workspace_detail"),
    path("workspaces/<slug:workspace_slug>/tags/add/", views.workspace_tag_add, name="workspace_tag_add"),
    path("workspaces/<slug:workspace_slug>/tags/<uuid:tag_id>/remove/", views.workspace_tag_remove, name="workspace_tag_remove"),
    path("workspaces/<slug:workspace_slug>/tags/save/", views.workspace_tags_save, name="workspace_tags_save"),
    path("apps/<slug:app_slug>/", views.app_detail, name="app_detail"),
    path("apps/<slug:app_slug>/tags/add/", views.app_tag_add, name="app_tag_add"),
    path("apps/<slug:app_slug>/tags/<uuid:tag_id>/remove/", views.app_tag_remove, name="app_tag_remove"),
    path("apps/<slug:app_slug>/tags/save/", views.app_tags_save, name="app_tags_save"),
    path("deploy/new/", views.deployment_workspace_new, name="deployment_workspace_new"),
    path("deploy/<slug:app_slug>/", views.deployment_workspace, name="deployment_workspace"),
    path("deploy/<slug:app_slug>/app-section/", views.deployment_workspace_app_section, name="deployment_workspace_app_section"),
    path("deploy/<str:blueprint_id>/blueprint-section/", views.deployment_workspace_blueprint_section, name="deployment_workspace_blueprint_section"),
    path("apps/<slug:app_slug>/deployments/<uuid:deployment_id>/teardown/", views.app_deployment_teardown, name="app_deployment_teardown"),
    path("apps/<slug:app_slug>/deployments/<uuid:deployment_id>/redeploy/", views.app_deployment_redeploy, name="app_deployment_redeploy"),
    path("apps/<slug:app_slug>/deployments/<uuid:deployment_id>/status/", views.app_deployment_status, name="app_deployment_status"),
    path("apps/<slug:app_slug>/deployments/<uuid:deployment_id>/teardown-confirm/", views.app_teardown_confirm, name="app_teardown_confirm"),
    path("environments/", views.environments, name="environments"),
    path("environments/<slug:environment_slug>/", views.environment_detail, name="environment_detail"),
    path("environments/<slug:environment_slug>/tags/add/", views.environment_tag_add, name="environment_tag_add"),
    path("environments/<slug:environment_slug>/tags/<uuid:tag_id>/remove/", views.environment_tag_remove, name="environment_tag_remove"),
    path("environments/<slug:environment_slug>/tags/save/", views.environment_tags_save, name="environment_tags_save"),
    path("security/hub/", views.security_hub, name="security_hub"),
    path("security/permissions/editor/", views.security_permissions_editor, name="security_permissions_editor"),
    path("security/permissions/<uuid:app_permission_request_id>/apply/", views.security_permissions_editor_apply, name="security_permissions_editor_apply"),
    path("security/permissions/<uuid:app_permission_request_id>/cancel/", views.security_permissions_editor_cancel, name="security_permissions_editor_cancel"),
    path("security/permissions/<uuid:app_permission_request_id>/update-statement/", views.security_permissions_editor_update_statement, name="security_permissions_editor_update_statement"),
    path("security/permissions/<uuid:app_permission_request_id>/description/", views.security_permissions_editor_description, name="security_permissions_editor_description"),
    path("security/permissions/<uuid:app_permission_request_id>/update-description/", views.security_permissions_editor_update_description, name="security_permissions_editor_update_description"),
    path("security/permissions/<uuid:app_permission_request_id>/refresh-resources/", views.security_permissions_editor_refresh_resources, name="security_permissions_editor_refresh_resources"),
    path("security/permissions/<uuid:app_permission_request_id>/service-group/", views.security_permissions_editor_service_group, name="security_permissions_editor_service_group"),
    path("security/permissions/<uuid:app_permission_request_id>/statements/", views.security_permissions_statements, name="security_permissions_statements"),
    # ABAC security
    path("security/people/", views.security_people, name="security_people"),
    path("security/people/default-role/", views.security_people_default_role, name="security_people_default_role"),
    path("security/people/<uuid:user_id>/", views.security_people_detail, name="security_people_detail"),
    path("security/people/<uuid:user_id>/attributes/add/", views.security_people_attribute_add, name="security_people_attribute_add"),
    path("security/people/<uuid:user_id>/attributes/<uuid:attribute_id>/remove/", views.security_people_attribute_remove, name="security_people_attribute_remove"),
    path("security/people/<uuid:user_id>/groups/add/", views.security_people_group_add, name="security_people_group_add"),
    path("security/people/<uuid:user_id>/groups/<uuid:membership_id>/remove/", views.security_people_group_remove, name="security_people_group_remove"),
    path("security/groups/", views.security_groups, name="security_groups"),
    path("security/groups/create/", views.security_group_create, name="security_group_create"),
    path("security/groups/<uuid:group_id>/", views.security_group_detail, name="security_group_detail"),
    path("security/groups/<uuid:group_id>/delete-confirm/", views.security_group_delete_confirm, name="security_group_delete_confirm"),
    path("security/groups/<uuid:group_id>/delete/", views.security_group_delete, name="security_group_delete"),
    path("security/groups/<uuid:group_id>/attributes/add/", views.security_group_attribute_add, name="security_group_attribute_add"),
    path("security/groups/<uuid:group_id>/attributes/<uuid:attribute_id>/remove/", views.security_group_attribute_remove, name="security_group_attribute_remove"),
    path("security/groups/<uuid:group_id>/members/add/", views.security_group_member_add, name="security_group_member_add"),
    path("security/groups/<uuid:group_id>/members/<uuid:membership_id>/remove/", views.security_group_member_remove, name="security_group_member_remove"),
    path("security/policies/", views.security_policies, name="security_policies"),
    path("security/policies/create/", views.security_policy_create, name="security_policy_create"),
    path("security/policies/<uuid:policy_id>/", views.security_policy_detail, name="security_policy_detail"),
    path("security/policies/<uuid:policy_id>/delete-confirm/", views.security_policy_delete_confirm, name="security_policy_delete_confirm"),
    path("security/policies/<uuid:policy_id>/delete/", views.security_policy_delete, name="security_policy_delete"),
    path("settings/", views.settings, name="settings"),
    path("settings/personal/", views.settings_personal, name="settings_personal"),
    path("settings/organization/", views.settings_organization, name="settings_organization"),
    path("settings/aws-accounts/", views.settings_aws_accounts, name="settings_aws_accounts"),
    path("settings/aws-accounts/add/", views.settings_aws_accounts_add, name="settings_aws_accounts_add"),
    path("settings/billing/", views.settings_billing, name="settings_billing"),
    path("settings/git-integrations/", views.settings_git_integrations, name="settings_git_integrations"),
    path("random-quote/", views.random_quote, name="random_quote"),
    path("switch-organization/", views.switch_organization, name="switch_organization"),

    # Authentication
    path("auth/login/", views.auth_login, name="login"),
    path("auth/callback/", views.auth_callback, name="auth_callback"),
    path("auth/logout/", views.auth_logout, name="logout"),
    path("oidc/login/", views.oidc_login, name="oidc_login"),
    path("oidc/callback/", views.oidc_callback, name="oidc_callback"),

    # Onboarding
    path("onboarding/", views.onboarding, name="onboarding"),

    # GitHub App OAuth
    path("github/connect", views.github_connect, name="github_connect"),
    path("github/callback", views.github_callback, name="github_callback"),
    path("github/setup", views.github_callback, name="github_setup"),  # Setup URL uses same handler

    # API endpoints
    #  - aws_install_account_callback: called by Lambda after customer deploys the CloudFormation stack, not browsers
    path("api/aws/install-account-callback", views.aws_install_account_callback, name="aws_install_account_callback"),
    #  - github_webhook: receives push/installation events from GitHub
    path("api/github/webhook", views.github_webhook, name="github_webhook"),

    # Chat / Agent
    path("chat/app_deploy/<slug:workspace_slug>/<str:repo_owner>/<str:repo_name>/", views.chat_app_deploy, name="chat_app_deploy_with_owner"),
    path("chat/app_deploy/<slug:workspace_slug>/<str:repo_name>/", views.chat_app_deploy, name="chat_app_deploy"),
    path("chat/", views.chat_list, name="chat_list"),
    path("chat/new/", views.chat_new, name="chat_new"),
    path("chat/<uuid:conversation_id>/", views.chat_view, name="chat_view"),
    path("chat/<uuid:conversation_id>/send/", views.chat_send, name="chat_send"),
    path("chat/<uuid:conversation_id>/stream/", views.chat_stream, name="chat_stream"),
    path("chat/<uuid:conversation_id>/messages/", views.chat_messages, name="chat_messages"),
    path("chat/<uuid:conversation_id>/close/", views.chat_close, name="chat_close"),
    path("chat/<uuid:conversation_id>/fork/", views.chat_fork, name="chat_fork"),
    path("chat/<uuid:conversation_id>/title/", views.chat_conversation_title, name="chat_conversation_title"),
    path("chat/<uuid:conversation_id>/cost/", views.chat_conversation_cost, name="chat_conversation_cost"),
]
